### ISSUE TITLE
Log and Protokoll text can't be selected

### ISSUE THREAD

**Issue by finsterwalder** [maza70/ZPush#1]
In the log-view and in the protocol of an executed job text can't be selected and copied.
This makes it a little harder to report a problem.
Alternatively a "send log to developer" could be implemented.

**Comment by maza70** [comment]
I'll think about it

**Comment by maza70** [comment]
You can now save the log to SdCard. 
The file is a text file and can open in the browser or send via Email.
Alternative you can send the log automatically over the Button "Email to support" in the Info page.
